[project]
name = "basic-mlops"
version = "0.1.0"
description = "This project is built for MLOps study."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "pyspark>=4.1.0",
]
